name = "hospital_api"
compatibility_date = "2023-12-01"

[vars]
AUTH_TOKEN = "12345"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "hospital"
database_id = "01c59215-69c3-4f8d-bc67-ba7f641a3d35"
